# **Pytorch cheat sheet**

In [1]:
import torch                # importing PyTorch 
print(torch.__version__)    # check for PyTorch version 
#device = "cuda" if torch.cuda.is_avalable() else "cpu"  # used to check device for computation, not a advisable command on google colab  
device = "cpu"

1.8.1+cu101


Creating the first Tensor and it's properties

In [2]:
#Creating Tensor 

my_torch = torch.tensor([[1,2,3],[4,5,6]], dtype =  torch.float32 , device ='cpu',requires_grad = True)
# required grad is used when we used backprop 

print(my_torch)#Printing my tensor

print(my_torch.dtype)#printing datatype of tensor 

print(my_torch.device)#Printing the device name used for processing 

print(my_torch.shape)#Print the tensor shape 

print(my_torch.requires_grad)#print fi ti requires grad or not 

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


Other common initiation methods 

In [3]:
x = torch.empty(size =(3,3))  #Tensor would have garbage values at all it's parts which would be random 
print(x)
x = torch.zeros((3,3))
print(x)
x = torch.rand((3,3))  # Normal distribution from 0,1
print(x)
x = torch.ones((3,3))
print(x)
x = torch.eye(3,3) # Identity matrix , no double brackets in identity matrices 
print(x)
x = torch.arange(start = 0 ,end =5,step =0.5) #inclusive start exclusive end 
print(x)
x = torch.linspace(start= 0 ,end =5 ,steps =10) # inclusive start inclusive ned with steps number of points 
print(x)
x = torch.empty(size =(1,5)).normal_(mean =0, std =1) # distribute data from 1 to 5 with a standard deviation of 1 
print(x)
x = torch.empty(size = (1,5)).uniform_(0,1)
print(x)
x = torch.diag(torch.ones(3)) # all the diagonal elements would be one or as mentioned in the inner dimention 
print(x)

tensor([[7.6639e+26, 3.0855e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9637, 0.1056, 0.2356],
        [0.5305, 0.7225, 0.8348],
        [0.4060, 0.4815, 0.3171]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000])
tensor([0.0000, 0.5556, 1.1111, 1.6667, 2.2222, 2.7778, 3.3333, 3.8889, 4.4444,
        5.0000])
tensor([[ 0.6643, -1.1021,  0.3778,  0.2979, -0.7050]])
tensor([[0.8683, 0.8613, 0.5116, 0.1604, 0.2206]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


How to initialize and convert tensor to other types (int float and double )

In [4]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool()) #applies boolean operator
print(tensor.short()) #convert to int16
print(tensor.long()) # to int64
print(tensor.half()) # to float16
print(tensor.float()) #float 32bit 
print(tensor.double())#float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


Array to tensor conversion and vice versa

In [5]:
import numpy as np 
np_array = np.zeros((5,5)) # numpy array of 5x5
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

Tensor math and comaprison operation 

In [6]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
#addition
z1 = torch.empty(3)
torch.add(x,y, out =z1)
print(z1)

z2 =  torch.add(x,y)
print(z2)

z = x + y #recommended one 
print(z)

#substraction 

z = x-y
print(z)

#division

z=torch.true_divide(x,y) # element wise division if both of them are of the same shape
print(z)
z = torch.true_divide(x,2) # division of each element by 2
print(z)

#implace operation

t = torch.zeros(3)
t.add_(x)
t += x # t= t+x is no implace 

#exponenciation

z =x.pow(2)
print(z)
z =x**2
print(z)

#simple comparison

z = x > 0
print(z)

#matrix multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) #element wise muliplication
print(x3)

x3 = x1.mm(x2)  #element wise multiplication 
print(x3)

#matrix expoenetiation 

matrix_exp = torch.rand((5,5))
print(matrix_exp.matrix_power(3)) # the shape is maintained 

#element wise multiplication 

z = x*y 
print(z)

#dot product

z = torch.dot(x,y) # Multiply each element and sum 
print(z)

# batch matrix multiplication 

batch =32
n = 10
m = 20
p = 30

tensor1 = torch.rand(batch,n,m)
tensor2 = torch.rand(batch,m,p)
out_bmm = torch.bmm(tensor1,tensor2)  # shape would be batch , n , p

# examples of broacasting 

x1 = torch.rand(5,5)
x2 = torch.rand(1,5)

z = x1-x2 #  the row of x2 would expand so that it matches with the row of x2 and there would be a batchwise substraction of each row of x2 from x1
print(x1)
print(x2)
print(z)

z = x1 ** x2

print(z)

# other useful tensor operations 

sum_x = torch.sum(x, dim = 0) #dim is the simention of a tensor in which we need to sum over 
print(sum_x)

values,indices = torch.max(x,dim = 0) # can also do x.max(dim = 0)
print(values, indices)
values,indices = torch.min(x,dim = 0) # can also do x.min(dim = 0)
print(values, indices)

abs_x = torch.abs(x)  # can also do x.max()
z = torch.argmax(x,dim = 0) # returns index of the one hwich is the maximum ; special case of the max function 
print(z)
z = torch.argmin(x,dim = 0)
print(z) 

mean_x = torch.mean(x.float(),dim = 0) # for mean the datatype should be float 
print(mean_x)

z = torch.eq(x,y) # element wise see if the elements are equal 
print(z)
 
sorted_y, indices = torch.sort(y, dim = 0, descending = False) # Sort in ascending order and also returns the indices which we need to swap 
print(indices) 

# clamp function 

# How the function works is it takes the vector x and all the values less than 0 are taken as zero 
# and all the values greater than ten(10) are taken as 10
# ReLu is a special case of clamp function 
z =  torch.clamp(x, min = 0, max = 10)

x = torch.tensor([1,0,1,1], dtype = torch.bool)
z = torch.any(x) # returns true if nay of the value in x is true 
print(z)
z = torch.all(x) # returns true if all of the values are true 
print(z)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([0.5000, 1.0000, 1.5000])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([True, True, True])
tensor([[1.7633, 2.1221, 2.2166],
        [1.9693, 1.7481, 2.1166]])
tensor([[1.7633, 2.1221, 2.2166],
        [1.9693, 1.7481, 2.1166]])
tensor([[2.1789, 3.4585, 2.4498, 2.6378, 1.9337],
        [1.5661, 2.6530, 1.7624, 1.8398, 1.4510],
        [2.4035, 3.9570, 2.6042, 2.8256, 2.1504],
        [2.3166, 3.6886, 2.5509, 2.6682, 2.0378],
        [2.3794, 3.5880, 2.5828, 2.8000, 1.9606]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[0.1850, 0.4252, 0.2628, 0.5987, 0.9797],
        [0.1305, 0.3096, 0.2194, 0.2141, 0.9062],
        [0.7981, 0.1307, 0.7868, 0.1401, 0.4079],
        [0.5894, 0.5304, 0.2810, 0.3841, 0.7131],
        [0.8090, 0.9887, 0.2893, 0.5090, 0.1732]])
tensor([[0.5786, 0.2303, 0.3017, 0.7720, 0.1161]])
tensor([[-0.3936,  0.1950, -0.0389, -0.1733,  0.8636],
      

Indexing in the tensor 

In [7]:
batch_size = 10
features = 25
x = torch.rand(batch_size, features)
print(x[0].shape)# x[0,:]

print(x[:,0].shape)

# how to get the first 10 features of the third example 
#2 = is the third example 
print(x[2,0:10])

x[0,0] = 100

# fancy indexing 

x =  torch.arange(10)
indices = [2, 5, 8]
print(x[indices]) # pick out the 2,5,8 element from the x

x = torch.rand(3,5)
rows = torch.tensor([1,0])
col = torch.tensor([4,0])
print(x[rows,col])

#more advanced indexing 

x = torch.arange(10)

print(x[(x<2)| (x >8) ])
print(x[(x>2) & (x <8) ])

print(x.remainder(2)==0)

#useful operations

print(torch.where(x>5,x,x*2)) # if it satisfies the condition then x otherwise 2*x
print(torch.tensor([0,0,1,2,2,3,4]).unique()) #returns unique elements of a tensor
print(x.ndimension()) #prints the number of dimention
print(x.numel()) # count the number of elements in x 


torch.Size([25])
torch.Size([10])
tensor([0.8908, 0.2857, 0.7304, 0.2952, 0.8143, 0.1332, 0.2679, 0.9255, 0.7489,
        0.7897])
tensor([2, 5, 8])
tensor([0.4432, 0.0144])
tensor([0, 1, 9])
tensor([3, 4, 5, 6, 7])
tensor([ True, False,  True, False,  True, False,  True, False,  True, False])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


Tensor reshaping 

In [8]:
x = torch.arange(9)

x_3x3 = x.view(3,3) # superior as it does not have the data loss but could be appliedto continuous data memory
print(x_3x3)

x_3x3 = x.reshape(3,3) # would work everytime but there is data loss
print(x_3x3)
y = x_3x3.t()
print(y)
#print(y.view(9)) # we'll get the error as it's not intractable 
print(y.contiguous().view(9))

x1 = torch.rand(2,5)
x2 = torch.rand(2,5)

print(torch.cat((x1,x2), dim =0).shape)
print(torch.cat((x1,x2), dim =1).shape)

z = x1.view(-1)
print(z.shape)

batch = 64
x = torch.rand(batch,2,5)
z = x.view(batch,-1)
print(z.shape)

#switching axis

z = x.permute(0,2,1)
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(1).shape)

x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1*1*10
print(x)

z =  x.squeeze(1)
print(z.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([10, 1])
torch.Size([10, 1])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
torch.Size([1, 10])
